name: deploy-on-aws

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # allow the runner to access the code in the repository

      - name: Login to Amazon ECR
        id: login-ecr # needed to reference this step later in the workflow
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # - name: Extract Git Tag
      #   id: extract_tag
      #   run: echo "::set-output name=TAG::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 324-devops-refcard-03
          IMAGE_TAG: latest # ${{ steps.extract_tag.outputs.TAG }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
