name: publish-on-github-registry

on:
  push:
    branches:
      - publish-github-registry

jobs:
  publish-on-github-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # - name: Extract Git Tag
      #   id: extract_tag
      #   run: echo "::set-output name=TAG::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ref-card-02:${{ github.sha }} #${{ steps.extract_tag.outputs.TAG }}
